### ISSUE TITLE
Make the build process automatic

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-js-api#17]

**Comment by eromano** [comment]
We can use the automatic travis npm Releasing:

https://docs.travis-ci.com/user/deployment/npm/

Conditon can be added on the release procedure and specify to release only when we add the tag release to the master branch like that:

```
deploy:
  ...
  on:
    tags: true
    branch: manster
```
